dist: focal
language: java

env:
  global:
    - GITHUB_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}

install:
  - mvn clean install


deploy:
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on: { branch: "master" }
